### ISSUE TITLE
Version 5.2 is messed up

### ISSUE THREAD

**Issue by LockMan007** [GarlicCookie/PNG-SD-Info-Viewer#1]
### **Version 5.2 bug report:**

1. Has no parameters.
2. The picture isn't centered. (Favors right side by a lot) using a 1080x1920 monitor, I don't know the DPI.
3. File list has no scroll bar. (yes I know in this example, the file list only has 3 pictures, but I tested it on a folder with lots of images, but I wanted to use this specific image as an example for the screenshot, which the file isn't long enough to show the scrollbars, but if I need to, i will take a screenshot of another folder that has a hundreds of image files and still no scrollbar)

_Version 5.1:_
_1. Shows Parameters correctly._
_2. Centers picture correctly._
_3. Displays scrollbars on file list correctly._

### **Version 5.x Requests:**
1. Add Drag-n-drop image.
2. Add Select Folder to the File Menu (don't remove the button, just add it to the menu also)
3. Almost Dark Mode, where it doesn't use pure black and uses the background color of GitHub instead.

.
![version5 2 missing-stuff](https://github.com/GarlicCookie/PNG-SD-Info-Viewer/assets/13595927/8239598b-4514-4bfa-bb32-61da5d81e095)

**Comment by LockMan007** [comment]
inserted at around line 100
NOTE: THIS DOES NOT HANDLE DRAG AND DROP OF A NON-IMAGE FILE AND WILL CRASH IF YOU TRY.
I'll try to add that code in later.
NOTE: DOES NOT SELECT FILE IN FILE LIST, but it does load the meta data and image.
```
                // this is my custom toad code toadcode /////////////////////////////////////////////////////
        private void frmMain_Load_1(object sender, EventArgs e)
        {
            picbImageDisplay.AllowDrop = true;
            picbImageDisplay.DragEnter += new DragEventHandler(frmMain_DragEnter);
            picbImageDisplay.DragDrop += new DragEventHandler(frmMain_DragDrop);
            this.AllowDrop = true;
            this.DragEnter += new DragEventHandler(frmMain_DragEnter);
            this.DragDrop += new DragEventHandler(frmMain_DragDrop);
        }

        private void frmMain_DragEnter(object? sender, DragEventArgs e)
        {
            //lblFolderSelected.Text = openPath;
            if (e.Data.GetDataPresent(DataFormats.FileDrop)) e.Effect = DragDropEffects.Copy;
        }

        private void frmMain_DragDrop(object? sender, DragEventArgs e)
        {
            if (e.Data.GetDataPresent(DataFormats.FileDrop))
            {
                string[] files = (string[])e.Data.GetData(DataFormats.FileDrop);
                string path = files[0];

                // Check if the path is a directory or a file
                if (System.IO.Directory.Exists(path))
                {
                    // The path is a directory
                    openPath = path;
                }
                else if (File.Exists(path))
                {
                    // The path is a file, so extract the directory path from it
                    openPath = Path.GetDirectoryName(path);
                }

                // Show the selected path in the UI
                lblFolderSelected.Text = openPath;

                // Go find images!
                findImagesInDirectory(openPath);

                // Load the image into the picturebox
                picbImageDisplay.ImageLocation = files[0];

                // Select the filename in the DataGridView
                string filename = Path.GetFileName(files[0]);

                lblFilename.Text = filename;
                //updateTagBox(filename);

                string selectedImage = lblFilename.Text;
                IEnumerable<MetadataExtractor.Directory> directories = ImageMetadataReader.ReadMetadata(openPath + "\\" + selectedImage);
                foreach (var directory in directories)
                    foreach (var tag in directory.Tags)
                    {
                        if (tag.Name == "Textual Data")
                        {
                            // Old style of EXIF pull.  Left for reference.
                            //textBox1.Text += ($"{directory.Name} \r\n - {tag.Name} = {tag.Description}");
                            //textBox1.Text += "\n";

                            // Parse text
                            string parsed = ($"{tag.Description}").Replace("Negative prompt:", "\r\n\r\nNegative Prompt:");
                            parsed = parsed.Replace("Steps:", "\r\n\r\nSteps:");
                            parsed = parsed.Replace("Sampler:", "\r\nSampler:");
                            parsed = parsed.Replace("CFG scale:", "\r\nCFG scale:");
                            parsed = parsed.Replace("Seed:", "\r\nSeed:");
                            parsed = parsed.Replace("Size:", "\r\nSize:");
                            parsed = parsed.Replace("Model hash:", "\r\nModel hash:");
                            parsed = parsed.Replace("Model:", "\r\nModel:");
                            parsed = parsed.Replace("Denoising strength:", "\r\nDenoising strength:");

                            // Update the textbox with the parsed string
                            txtParameters.Text += parsed;
                        }
                    }


            }
        }

```

**Comment by GarlicCookie** [comment]
Thanks for sending.  The new version was an attempt at fixing some resolution and scaling problems after switching to an ultrawide monitor.  Sounds like it didn't go too well. :(  The previous 5.1 should be ok.  I'll see if I can address.

I can take a look at drag n' drop at some point.  There are a few things to consider with that because of how the folder setting works.

**Comment by GarlicCookie** [comment]
Version 5.3 has been uploaded.  This is an attempt to fix the scaling issue.  I'd appreciate confirmation it is working. :)

Also added the Folder Selection to the File menu per request.

**Comment by LockMan007** [comment]
The Drag And Drop was brute forced to work, with originally no understanding of the code and gradually understanding more and more. I essentially copy/pasted code needed, which is generally not an efficient way of coding, but it works. I'll test out that version

**Comment by LockMan007** [comment]
> Version 5.3 has been uploaded. This is an attempt to fix the scaling issue. I'd appreciate confirmation it is working. :)
> 
> Also added the Folder Selection to the File menu per request.

The new Version 5.3 has no issues I notice.
Correctly centered, displays meta data.

_Another maybe suggestion is to allow resizing the bottom Parameters box, but that seems like it may be troublesome to code.
There is no Parameters box size that is best._
OH I DIDN'T NOTICE THE RESIZE BAR! AWESOME!

I switched to your software, because the Parameters is Multiline, while the other software I was using, was a single line, which is a bad design.

I suspect it may be possible to code it to either only show images with Meta Data or toggle that.

These are just things.
This is already my go-to recommended EXIF/Meta data viewing program of choice.

**Comment by GarlicCookie** [comment]
Awesome, I'm glad it is working now. :)
Glad you like it, also!  There's some handy tricks, like scrolling your mousewheel while on the image will navigate back and forth.  The "~" key will tag/untag images, making culling easy.  Holding middle-mouse over the image will let you move it around.

It's not perfect.  I think there's a weird issue with the column headers in detail mode, actually, but haven't had a chance to circle back to that yet. (Seed/model/model hash are mixed up, oops)

I am going to mark this issue closed since the scaling issue appears resolved.  I will circle back to your feature request for drag n' drop.  I think that would be handy, just need to think about how to handle the open folder.  (Does it switch to the dragged image's folder or stay where it was? Then what happens if you move to another image? etc.)

At some point, maybe I'll re-write with WPF instead so things like scaling and dark mode work better.

**Comment by LockMan007** [comment]
> 

i coded it to switch folder and load the meta data on drag and drop

**Comment by GarlicCookie** [comment]
Drag and drop has been added as well per request.

I opted for the following behavior:
1) If a FOLDER is dragged in, it will switch to that folder and display the images therein.
2) If a FILE is dragged in, it will stay on its existing folder, and just display the dragged in file.  The user can then continue to select items from the folder that was already open.
